services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: |
  pip install -r requirements.txt
  playwright install
    startCommand: python Renderbot.py
    plan: free
    autoDeploy: true
    envVars:
      - key: CONTROL_BOT_TOKEN
        value: "7990020438:AAHJ2-7l2JURUVgIV5tNliDiS53UsIbHbE4"
      - key: REPORT_BOT_TOKEN
        value: "7990743429:AAGtuHxeR8q2vbxoL-Bnq_gcP9-6-plddMk"
      - key: PORT
        value: "8080"
