services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python Renderbot.py
    plan: free
    autoDeploy: true
    envVars:
      - key: TOKEN
        value: "python Renderbot.py"
